% Lamination 

clc
clear
n = 1:20; %number of laminations

MES_AirBox = 2; %Maximum Element Size in air (mm)
MES_Conductors = 2; %Maximum Element Size in conductors (mm)
MES_Laminations = 0.15; %Maximum Element Size in the laminations (mm)

CoilTurns = 1000; %Number of turns on the coil
CoilCurrent = 1; %Amperes, current to get 1 T at the lamination center

%TO DO: 
%   - use a lamination steel that is conductive
%   - extract field results
%   - iterate to find desired field

for j = 1:length(n)
%% set up MagNet
toolMn = MagNet();
toolMn.open(0,0,true);
toolMn.setDefaultLengthUnit('millimeters', false);

%% MagNet Airbox
CsAir = CrossSectSolidRect( ...
        'name', 'Cond1', ...
        'dim_w',DimMillimeter(78),....
        'dim_h',DimMillimeter(90),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([-30,-30]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
compAir = Component( ...
        'name', 'Airbox', ...
        'crossSections', CsAir, ...
        'material', MaterialGeneric('name', 'AIR'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
compAir.make(toolMn,toolMn);
toolMn.viewAll();

%% Conductors

CsCleft = CrossSectSolidRect( ...
        'name', 'Cond1', ...
        'dim_w',DimMillimeter(2),....
        'dim_h',DimMillimeter(25),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,2.5]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
CsCright = CrossSectSolidRect( ...
        'name', 'Cond2', ...
        'dim_w',DimMillimeter(2),....
        'dim_h',DimMillimeter(25),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([16,2.5]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
condL = Component( ...
        'name', 'LeftCoil', ...
        'crossSections', CsCleft, ...
        'material', MaterialGeneric('name', 'Copper: 5.77e7 Siemens/meter'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
condL.make(toolMn,toolMn);
toolMn.viewAll();

condR = Component( ...
        'name', 'RightCoil', ...
        'crossSections', CsCright, ...
        'material', MaterialGeneric('name', 'Copper: 5.77e7 Siemens/meter'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );

condR.make(toolMn,toolMn);
toolMn.viewAll();

%% Laminations
lamT = 10/n(j); %lamination thickness
for i = 1:n(j)
    lamCS(i) = CrossSectSolidRect( ...
        'name', ['csLam' num2str(i)], ...
        'dim_w',DimMillimeter(lamT),....
        'dim_h',DimMillimeter(30),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([4 + lamT*(i-1),0]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
    %REPLACE THE MATERIAL WITH A CONDUCTIVE STEEL MATERIAL MODEL
    compLam(i) = Component( ...
        'name', ['Lam' num2str(i)], ...
        'crossSections', lamCS(i), ...
        'material', MaterialGeneric('name', 'Hiperco 50A 0.006 non-zero conductivity'), ... % M-19 24 Ga
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
    
    compLam(i).make(toolMn,toolMn);
    toolMn.viewAll();
end


%% Create and setup winding
coilName = mn_d_makeSimpleCoil(toolMn.mn, 1, [{'LeftCoil'}, {'RightCoil'}]);
mn_d_setparameter(toolMn.doc, coilName, 'WaveFormType', 'DC', ...
    get(toolMn.consts,'InfoStringParameter'));
mn_d_setparameter(toolMn.doc, coilName, 'Current', CoilCurrent, ...
    get(toolMn.consts,'infoNumberParameter'));
mn_d_setparameter(toolMn.doc, coilName, 'NumberOfTurns', CoilTurns, ...
    get(toolMn.consts,'infoNumberParameter'));


%% Setup Mesh
mn_d_setparameter(toolMn.doc, compAir.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_AirBox), ...
    get(toolMn.consts,'infoNumberParameter'));
mn_d_setparameter(toolMn.doc, condL.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Conductors), ...
    get(toolMn.consts,'infoNumberParameter'));
mn_d_setparameter(toolMn.doc, condR.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Conductors), ...
    get(toolMn.consts,'infoNumberParameter'));

for i = 1:length(compLam)
    mn_d_setparameter(toolMn.doc, compLam(i).name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Laminations), ...
    get(toolMn.consts,'infoNumberParameter'));
end

%% Solve it

% % sol = invoke(toolMn.doc, 'solveStatic2d');

% Set transient options
command = 'Call getDocument().beginUndoGroup("Set Transient Options", true)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().setFixedIntervalTimeSteps(0, 50, 5)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().deleteTimeStepMaximumDelta()';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().setParameter("", "TransientAveragePowerLossStartTime", "0%ms", infoNumberParameter)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().setParameter("", "TransientAveragePowerLossStopTime", "50%ms", infoNumberParameter)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().endUndoGroup()';
invoke(toolMn.mn, 'processCommand', command);

% Set a sinusoidal current
command = 'Call getDocument().getView().selectObject("Coil#1", infoSetSelection)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().beginUndoGroup("Set Coil#1 Properties", true)';
invoke(toolMn.mn, 'processCommand', command);
command = 'REDIM ArrayOfValues(2)';
invoke(toolMn.mn, 'processCommand', command);
command = 'ArrayOfValues(0)= 0';
invoke(toolMn.mn, 'processCommand', command);
command = 'ArrayOfValues(1)= 8.5';
invoke(toolMn.mn, 'processCommand', command);
command = 'ArrayOfValues(2)= 20';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().setSourceWaveform("Coil#1","SIN", ArrayOfValues)';
invoke(toolMn.mn, 'processCommand', command);
command = 'Call getDocument().endUndoGroup()';
invoke(toolMn.mn, 'processCommand', command);

sol = invoke(toolMn.doc, 'solveTimeHarmonic2d');
% sol = invoke(toolMn.doc, 'solveTransient2d');

%% Post-processing

% get iron ohmic losses
solution = invoke(toolMn.doc, 'getSolution');
for i = 1:length(compLam)
    OhmicLosses(i) = invoke(solution, 'getOhmicLossInConductor', int32(1), compLam(i).name);
end
TotalOhmicLossesTH(j) = sum(OhmicLosses);

% get |B| value at tooth center
invoke(toolMn.mn, 'processCommand', 'Set Sol = getDocument.getSolution');
invoke(toolMn.mn, 'processCommand', 'Set Mesh = Sol.getMesh(1)');
invoke(toolMn.mn, 'processCommand', 'Set Field = Sol.getSystemField(Mesh, "|B| smoothed")');
invoke(toolMn.mn, 'processCommand', 'ReDim FieldVals(0)');

command = ['Call Field.getFieldAtPoint(' num2str(9) ', ' num2str(15) ', 0 ,FieldVals)'];
invoke(toolMn.mn, 'processCommand', command);
invoke(toolMn.mn, 'processCommand', 'call setVariant(0,FieldVals(0),"MATLAB")');
BValuesTH(j) = invoke(toolMn.mn, 'getVariant', 0, 'MATLAB');

% save file and exit
FileName = [pwd '\lam_thickness_',num2str(lamT),'.mn'];
Doc=invoke(toolMn.mn, 'saveDocument', FileName);
invoke(toolMn.mn, 'exit');

end