clc
clear
[mn, doc] = mn_open();
set(mn, 'Visible', true);
mn_d_setDefaultLengthUnit(doc, 'millimeters', false);

breadloaf = compBreadloaf('name', 'loaf1', ...
    'dim_w', dimMillimeter(40), ...
    'dim_r', dimMillimeter(80), ...
    'dim_l', dimMillimeter(10), ...
    'dim_alpha', dimDegree(45).toRadians, ...
    'material', matGeneric('name', 'pm'), ...
    'location', compLocation('anchor_xyz', dimMillimeter([0,0,0]), ...
                            'rotate_xyz', dimDegree([0,0,0]).toRadians));
                        
loaf_segs = mn_drawBreadloaf(mn, breadloaf);
mn_dv_viewAll(mn);