clc
clear

%LIMITED TEST TO DEMONSTRATE FUNCTIONALITY
%ENHANCE FOR FULL IMPLEMENTATION


%% Define cross sections
    
bread1 = CrossSectBreadloaf( ...
        'name', 'breadloaf1', ...
        'dim_l', DimMillimeter(1.5), ...
        'dim_w', DimMillimeter(4), ...
        'dim_alpha', DimDegree(60), ...
        'dim_r', DimMillimeter(2), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0) ...
        ) ...
        );
bread2 = bread1.clone('breadloaf2', 'dim_l', DimMillimeter(1.9));

comp1 = Component( ...
        'name', 'comp1', ...
        'crossSections', bread1, ...
        'material', MaterialGeneric('name', 'pm'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(80)) ...
        );
    
comp2 = comp1.clone('comp2', 'crossSections', bread2);

%% This is example of a potential bug: comp3 has the same name as comp1, and bread3 has the same name as bread1.
comp3 = comp2.clone('comp1')
bread3 = bread2.clone('breadloaf1')

