clc
clear
[mn, doc] = mn_open();
set(mn, 'Visible', true);
mn_d_setDefaultLengthUnit(doc, 'millimeters', false);
    
  rect = compHollowRect('name', ['rect'], ...
        'dim_t1', dimMillimeter(5), ...
        'dim_t2', dimMillimeter(3),...
        'dim_t3', dimMillimeter(2),...
        'dim_t4', dimMillimeter(2),...
        'dim_l_o', dimMillimeter(100), ...
        'dim_b_o', dimMillimeter(30),...
        'material', matGeneric('name', 'iron'), ...
        'location', compLocation('anchor_xyz', dimMillimeter([0,0,0]),...
        'rotate_xyz', dimDegree([0,0,0]).toRadians));
                    
    line_segs = mn_drawHollowRect(mn, rect);
    mn_dv_viewAll(mn);