clc
clear

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;

%% Define cross sections

hollowCylinder = CrossSectHollowCylinder( ...
        'name', 'hollowCylinder', ...
        'dim_d_a', dimMillimeter(4), ...
        'dim_r_o', dimMillimeter(80), ...
        'dim_depth', DimMillimeter(1), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'rotate_xy', DimDegree([0,0]).toRadians() ...
        ) ...
        );

%% Define components

cs = hollowCylinder;

comp1 = Component( ...
        'name', 'comp1', ...
        'cross_sections', cs, ...
        'material', MaterialGeneric('name', 'pm'), ...
        'make_solid', MakeSolidBase(), ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ) ...
        );

%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open(0,0,true);
    toolMn.setDefaultLengthUnit('millimeters', false);

    comp1.make(toolMn);

    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.make(toolTikz);

    toolTikz.close();
end
