clc
clear
[mn, doc] = mn_open();
set(mn, 'Visible', true);
mn_d_setDefaultLengthUnit(doc, 'millimeters', false);

for i = 1:4
    
    breadloaf(i) = compBreadloaf('name', 'loaf1', ...
        'dim_w', dimMillimeter(30), ...
        'dim_r', dimMillimeter(30), ...
        'dim_l', dimMillimeter(10), ...
        'dim_alpha', dimDegree(60).toRadians, ...
        'material', matGeneric('name', 'pm'), ...
        'location', compLocation('anchor_xyz', dimMillimeter([0,0,0]), ...
                       'rotate_xyz', dimDegree([0,0,90*(i-1)]).toRadians));

    loaf_segs = mn_drawBreadloaf(mn, breadloaf(i));
    mn_dv_viewAll(mn);

end
