clc
clear all

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;

%% Define cross sections

hollowCylinder1 = CrossSectHollowCylinder( ...
        'name', 'hollowCylinder1', ...
        'dim_d_a', DimMillimeter(4), ...
        'dim_r_o', DimMillimeter(80), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );

%% Define components

cs = hollowCylinder1;

comp1 = Component( ...
        'name', 'comp1', ...
        'crossSections', cs, ...
        'material', MaterialGeneric('name', 'pm'), ...
        'makeSolid', MakeSimpleExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(80)) ...
        );

%% Clone Example

% comp1
comp1;

% comp2
comp2 = comp1.clone('name', 'comp2');

% comp3
comp3 = comp2.clone('name', 'comp3');

% Q: How can you make sure the comp3 cloned from comp2 has different name from comp1?
% For example, you can replace with something below. Uncomment and have a try.
% comp3 = comp2.clone('name', 'comp1');
