clc
clear

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;

%% Define cross sections
   
HollowRect = CrossSectHollowRect( ...
        'name', 'HollowRect', ...
        'dim_t1', DimMillimeter(3), ...
        'dim_t2', DimMillimeter(3), ...
        'dim_t3', DimMillimeter(3),...
        'dim_depth', DimMillimeter(0),...
        'dim_t4', DimMillimeter(3),....
        'dim_l_o',DimMillimeter(10),....
        'dim_b_o',DimMillimeter(20),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,5]), ...
            'rotate_xy', DimDegree([0,45]).toRadians() ...
        ) ...
        );
    
%% Define components

cs = HollowRect;

comp1 = Component( ...
        'name', 'comp1', ...
        'cross_sections', cs, ...
        'material', MaterialGeneric('name', 'pm'), ...
        'make_solid', MakeSolidBase(), ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ) ...
        );

%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open(0,0,true);
    toolMn.setDefaultLengthUnit('millimeters', false);

    comp1.make(toolMn);

    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.make(toolTikz);

    toolTikz.close();
end
