clc
clear

DRAW_MAGNET = 0;
DRAW_TIKZ   = 0;
DRAW_JMAG = 1;

%% Define cross sections
    
bread1 = CrossSectBreadloaf( ...
        'name', 'breadloaf1', ...
        'dim_l', DimMillimeter(1.5), ...
        'dim_w', DimMillimeter(4), ...
        'dim_alpha', DimDegree(60), ...
        'dim_r', DimMillimeter(2), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0) ...
        ) ...
        );
    
bread2 = CrossSectBreadloaf( ...
        'name', 'breadloaf1', ...
        'dim_l', DimMillimeter(1.5), ...
        'dim_w', DimMillimeter(4), ...
        'dim_alpha', DimDegree(60), ...
        'dim_r', DimMillimeter(2), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,4]), ...
            'theta', DimDegree(180) ...
        ) ...
        );
    
bread3 = CrossSectBreadloaf( ...
        'name', 'breadloaf1', ...
        'dim_l', DimMillimeter(1.5), ...
        'dim_w', DimMillimeter(4), ...
        'dim_alpha', DimDegree(60), ...
        'dim_r', DimMillimeter(2), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([10,2]), ...
            'theta', DimDegree(180) ...
        ) ...
        );    
    
%% Define components

cs1 = [bread1];

comp1 = Component( ...
        'name', 'comp1', ...
        'crossSections', cs1, ...
        'material', MaterialGeneric('name', 'M19: USS Transformer 72 -- 29 Gage'), ...
        'makeSolid', MakeExtrude( ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ), ...
        'dim_depth', DimMillimeter(3)) ...
        );
    
cs2 = [bread2];

comp2 = Component( ...
        'name', 'comp2', ...
        'crossSections', cs2, ...
        'material', MaterialGeneric('name', 'M19: USS Transformer 72 -- 29 Gage'), ...
        'makeSolid', MakeExtrude( ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ), ...
        'dim_depth', DimMillimeter(3)) ...
        );

comp3 = Component( ...
        'name', 'comp3', ...
        'crossSections', bread3, ...
        'material', MaterialGeneric('name', 'M19: USS Transformer 72 -- 29 Gage'), ...
        'makeSolid', MakeRevolve( ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ), ...
        'dim_center', [DimMillimeter(0) DimMillimeter(2)], ...
        'dim_axis', [DimMillimeter(0), DimMillimeter(1)], ...
        'dim_angle', DimDegree(180)) ...
        );
    
%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open(0,0,true);
    toolMn.setDefaultLengthUnit('millimeters', false);

    comp1.make(toolMn, toolMn);
    comp2.make(toolMn, toolMn);
    comp3.make(toolMn, toolMn);
    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.draw(toolTikz);

    toolTikz.close();
end

%% Draw via JMAG
path = pwd;
fileName = 'test1';

if (DRAW_JMAG)
    toolJd = JMAG();
    toolJd.setVisibility(true);
    toolJd.open();
    comp1.make(toolJd,toolJd);
    comp2.make(toolJd,toolJd);
    comp3.make(toolJd,toolJd);
    toolJd.save(path, fileName);
    toolJd.close();
    delete(toolJd);
end