clc
clear

%LIMITED TEST TO DEMONSTRATE FUNCTIONALITY
%ENHANCE FOR FULL IMPLEMENTATION


%% Define cross sections
    
bread1 = CrossSectBreadloaf( ...
        'name', 'breadloaf1', ...
        'dim_l', DimMillimeter(1.5), ...
        'dim_w', DimMillimeter(4), ...
        'dim_alpha', DimDegree(60), ...
        'dim_r', DimMillimeter(2), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0) ...
        ) ...
        );
bread2 = bread1.clone('breadloaf2', 'dim_l', DimMillimeter(1.9));


