clc
clear

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;
DRAW_JMAG = 1;
%% Define cross sections

stator1 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 3, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([-170,-90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );
stator2 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 4, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,-90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );
stator3 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 5, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([170,-90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );
stator4 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 6, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([-170,90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );
stator5 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 7, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );    
stator6 = CrossSectInnerRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(40), ...
        'dim_alpha_so', DimDegree(20), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(5), ...
        'dim_d_sp', DimMillimeter(10), ...
        'dim_d_st', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(15), ...
        'dim_w_st', DimMillimeter(13), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 8, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([170,90]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
        );
    
%% Define components

cs = [stator4];%, stator2, stator3, stator4, stator5, stator6];

comp1 = Component( ...
        'name', 'comp1', ...
        'crossSections', cs, ...
        'material', MaterialGeneric('name', 'M19: USS Transformer 72 -- 29 Gage'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(15)) ...
        );

%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open(0,0,true);
    toolMn.setDefaultLengthUnit('millimeters', false);

    comp1.make(toolMn, toolMn);

    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.draw(toolTikz);

    toolTikz.close();
end


if (DRAW_JMAG)
    toolJd = JMAG();
    toolJd.open(0,0,true);
    comp1.make(toolJd,toolJd);
    
end
