clc
clear

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;

%% Define cross sections

arc1 = CrossSectArc( ...
        'name', 'arc1', ...
        'dim_d_a', DimMillimeter(1), ...
        'dim_r_o', DimMillimeter(10), ...
        'dim_depth', DimMillimeter(10), ...
        'dim_alpha', DimDegree(45).toRadians(), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'rotate_xy', DimDegree(0).toRadians() ...
        ) ...
        );
    
trap1 = CrossSectTrapezoid( ...
        'name', 'trapezoid1', ...
        'dim_h', DimMillimeter(1), ...
        'dim_w', DimMillimeter(4), ...
        'dim_theta', DimDegree(60).toRadians(), ...
        'dim_depth', DimMillimeter(1), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'rotate_xy', DimDegree(0).toRadians() ...
        ) ...
        );
    
stator1 = CrossSectInnerRotorPMStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(30), ...
        'dim_alpha_so', DimDegree(15), ...
        'dim_r_si', DimMillimeter(40), ...
        'dim_d_so', DimMillimeter(40), ...
        'dim_d_sp', DimMillimeter(40), ...
        'dim_d_st', DimMillimeter(40), ...
        'dim_d_sy', DimMillimeter(40), ...
        'dim_w_st', DimMillimeter(40), ...
        'dim_r_st', DimMillimeter(40), ...
        'dim_r_sf', DimMillimeter(40), ...
        'dim_r_sb', DimMillimeter(40), ...
        'slots', 4, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'rotate_xy', DimDegree(0).toRadians() ...
        ) ...
        );
    
%% Define components

cs = [arc1 trap1];

comp1 = Component( ...
        'name', 'comp1', ...
        'cross_sections', cs, ...
        'material', MaterialGeneric('name', 'pm'), ...
        'make_solid', MakeSolidBase(), ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ) ...
        );

%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open(0,0,true);
    toolMn.setDefaultLengthUnit('millimeters', false);

    comp1.make(toolMn);

    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.make(toolTikz);

    toolTikz.close();
end
