clc
clear

toolMn = MagNet();
toolMn.open(0,0,true);
toolMn.setDefaultLengthUnit('millimeters', false);

arc1 = CrossSectArc( ...
        'name', 'arc1', ...
        'dim_d_a', DimMillimeter(1), ...
        'dim_r_o', DimMillimeter(10), ...
        'dim_depth', DimMillimeter(10), ...
        'dim_alpha', DimDegree(45).toRadians(), ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'rotate_xy', DimDegree([0,0]).toRadians() ...
        ), ...
        'drawer', toolMn ...
        );
    
comp1 = Component( ...
        'name', 'comp1', ...
        'cross_sections', [arc1], ...
        'material', MaterialGeneric('name', 'pm'), ...
        'make_solid', MakeSolidBase(), ...
        'location', Location3D( ...
            'anchor_xyz', DimMillimeter([0,0,0]), ...
            'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
        ) ...
        );

comp1.make();

toolMn.viewAll();
