clc
clear

DRAW_MAGNET = 1;
DRAW_TIKZ   = 0;

%% Define cross sections

rotor1 = CrossSectOuterRotor( ...
        'name', 'rotor1', ...
        'dim_alpha_rs', DimDegree(20), ...
        'dim_alpha_rm', DimDegree(60), ...
        'dim_R_ro', DimMillimeter(30), ...
        'dim_d_rp', DimMillimeter(5), ...
        'dim_d_ri', DimMillimeter(5), ...
        'dim_d_rs', DimMillimeter(8), ...
        'dim_P', 2, ...
        'dim_S', 1, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
);

%% Define components

cs = [rotor1];

comp1 = Component( ...
        'name', 'comp1', ...
        'crossSections', cs, ...
        'material', MaterialGeneric('name', 'M19: USS Transformer 72 -- 29 Gage'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(15)) ...
        );

%% Draw via MagNet

if (DRAW_MAGNET)
    toolMn = MagNet();
    toolMn.open();
    toolMn.setVisibility(1);
    toolMn.setDefaultLengthUnit('DimMillimeter', false);

    comp1.make(toolMn, toolMn);

    toolMn.viewAll();
end

%% Draw via TikZ

if (DRAW_TIKZ)
    toolTikz = TikZ();
    toolTikz.open('output.txt');

    comp1.draw(toolTikz);

    toolTikz.close();
end
