clc
clear

FemmProblem = newproblem_mfemm('pl', ...
                               'Frequency', 0, ...
                               'LengthUnits', 'millimeters');

for i = 1:4  
    
    hollowCylinder(i) = compHollowCylinder('name',...
        ['hollowCylinder' num2str(i)], ...
        'dim_d_a', dimMillimeter(4), ...
        'dim_r_o', dimMillimeter(80), ...
        'material', matGeneric('name', 'pm'), ...
        'location', compLocation('anchor_xyz', dimMillimeter([80*i,0,0]), ...
                        'rotate_xyz', dimDegree([0,0,0]).toRadians));

    FemmProblem = xfemm_drawHollowCylinder(FemmProblem, hollowCylinder(i));
end
plotfemmproblem(FemmProblem);